### ISSUE TITLE
no working using demo.py

### ISSUE THREAD

**Issue by stphtan94117** [jinfagang/SegAnythingPro#1]
i type python demo.py -i data\inpaint_demo.jpg -p 'dog'
get error message
 line 84, in main
    basename = iter.crt_filename.split(".")[0]
AttributeError: 'ImageSourceIter' object has no attribute 'crt_filename'

![image](https://user-images.githubusercontent.com/110151053/231437895-3d658d6b-58c2-45c5-b6d7-c8af64ac287e.png)

**Comment by jinfagang** [comment]
hello, upgrade alfred-py to 3.0.6 or install from `pip install git+https://github.com/jinfagang/alfred`

**Comment by stphtan94117** [comment]
你好
測試成功，但用自己的圖片，為何無法完整去除車子? 照片結果只去除一輛，但明明所有車輛都有偵測到
![000014-inpaint](https://user-images.githubusercontent.com/110151053/231449612-6cd546fc-5674-457c-977f-beec75382047.png)
![000014-res_det](https://user-images.githubusercontent.com/110151053/231449643-fb90b0b2-c350-4d3c-99ca-291683d0508c.png)
![000014-res_masks](https://user-images.githubusercontent.com/110151053/231449661-7bbed3d7-d320-483c-9875-8d5dccd14554.png)
![000014-src](https://user-images.githubusercontent.com/110151053/231449675-b1310008-197f-487a-a945-281e46d7f95f.png)

**Comment by jinfagang** [comment]
Hi, this is because I am just taking first mask, you can modify the mask output and combine them togather. You can try and please make a PR for this feature.

**Comment by stphtan94117** [comment]
> Hi, this is because I am just taking first mask, you can modify the mask output and combine them togather. You can try and please make a PR for this feature.

你可以幫忙提交PR嗎 不太會使用 謝謝
另外想詢問 遇到比較大的圖 例如4000*3000像素 CUDA mem會不足
本身PC 是GPU 3080 10G ram
